name: CommandSpy
main: TitaniumLB\CommandSpy\Main
version: 1.0.0
api: 3.0.0
author: TitaniumLB
description: Cool Commandspy by Titanium

commands:
  commandspy:
    description: Enter Spy-Mode
    aliases: ["cspy"]
permissions:
  commandspy.cmd:
    default: op
